# Generated by Django 4.2.19 on 2025-02-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_rename_date_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Date',
            new_name='date',
        ),
    ]
