# Generated by Django 4.2.19 on 2025-02-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_rename_date_transaction_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date',)},
        ),
    ]
