# Generated by Django 4.2.19 on 2025-02-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorrecord',
            name='superviseename',
        ),
        migrations.AddField(
            model_name='supervisorrecord',
            name='superviseeid',
            field=models.IntegerField(null=True),
        ),
    ]
