# Generated by Django 4.2.19 on 2025-02-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0002_remove_supervisorrecord_superviseename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorrecord',
            name='superviseeid',
            field=models.IntegerField(),
        ),
    ]
