# Generated by Django 4.2.19 on 2025-02-21 05:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Supervisor', '0003_alter_supervisorrecord_superviseeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superviseeid', models.IntegerField()),
                ('dateandtime', models.DateTimeField(default=datetime.datetime(2025, 2, 21, 13, 12, 31, 48387))),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionRequestHistory',
            fields=[
                ('activityhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Supervisor.activityhistory')),
                ('pending', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            bases=('Supervisor.activityhistory',),
        ),
        migrations.CreateModel(
            name='SupervisorActivityHistory',
            fields=[
                ('activityhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Supervisor.activityhistory')),
            ],
            bases=('Supervisor.activityhistory',),
        ),
        migrations.CreateModel(
            name='PendingConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superviseeid', models.IntegerField()),
                ('dateandtime', models.DateTimeField(default=datetime.datetime(2025, 2, 21, 13, 12, 31, 48034))),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supervisor.activityhistory')),
                ('supervisorrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supervisor.supervisorrecord')),
            ],
        ),
    ]
