# Generated by Django 4.2.19 on 2025-02-21 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0005_alter_activityhistory_dateandtime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityhistory',
            options={'ordering': ('-dateandtime',)},
        ),
        migrations.RenameField(
            model_name='currentactivity',
            old_name='activity',
            new_name='activityhistory',
        ),
        migrations.AlterField(
            model_name='activityhistory',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 17, 15, 56, 281656)),
        ),
        migrations.AlterField(
            model_name='pendingconnections',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 17, 15, 56, 281295)),
        ),
    ]
