# Generated by Django 4.2.19 on 2025-02-21 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0006_alter_activityhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityhistory',
            name='activitytype',
            field=models.CharField(choices=[('Supervisor Login', 'Supervisor Login'), ('Supervisor End', 'Supervisor End'), ('Supervisee End', 'Supervisee End'), ('Connection Request', 'Connection Request')], default='Connection Request', max_length=100),
        ),
        migrations.AlterField(
            model_name='activityhistory',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 19, 1, 25, 454855)),
        ),
        migrations.AlterField(
            model_name='pendingconnections',
            name='dateandtime',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 19, 1, 25, 454465)),
        ),
        migrations.DeleteModel(
            name='SupervisorActivityHistory',
        ),
    ]
